HeathHopkins/Models/Contact.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeathHopkins.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
    }
}

HeathHopkins/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HeathHopkins.Models;

namespace HeathHopkins.Controllers
{
    public class ContactController : Controller
    {
        private ContactRepository repo = new ContactRepository(new HeathHopkinsEntities());
        
        public ActionResult Index()
        {
            try
            {
                return View(repo.All().ToList());   
            }
            catch (Exception ex)
            {
                Util.Log(ex);
            }
            return View("Error");
        }
        
        public ActionResult Details(int id)
        {
            try
            {
                return View(repo.Single(id));
            }
            catch (Exception ex)
            {
                Util.Log(ex);
            }
            return View("Error");
        }
        
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Contact contact)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View(contact);
                repo.Add(contact);
                repo.Save();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Util.Log(ex);
            }
            return View("Error");
        }
        
        public ActionResult Edit(int id)
        {
            try
            {
                return View(repo.Single(id));
            }
            catch (Exception ex)
            {
                Util.Log(ex);
            }
            return View("Error");
        }


        [HttpPost]
        public ActionResult Edit(int id, Contact contact)
        {
            try
            {
                var record = repo.Single(id);
                UpdateModel<Contact>(record);
                if (!ModelState.IsValid)
                    return View(record);
                repo.Save();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Util.Log(ex);
            }
            return View("Error");
        }

        public ActionResult Delete(int id)
        {
            try
            {
                var contact = repo.Single(id);
                return View(contact);
            }
            catch (Exception ex)
            {
                Util.Log(ex);
            }
            return View("Error");
        }
        
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                var contact = repo.Single(id);
                repo.Remove(contact);
                repo.Save();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Util.Log(ex);
            }
            return View("Error");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && repo != null)
            {
                repo.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HeathHopkins/Views/Contact/Create.cshtml
@model HeathHopkins.Models.Contact

@{
    ViewBag.Title = "Add Contact";
}

<h2>@ViewBag.Title</h2>

@{Html.RenderPartial("Form", Model);}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HeathHopkins/Views/Contact/Delete.cshtml
@model HeathHopkins.Models.Contact

@{
    ViewBag.Title = "Delete Contact";
}

@section Scripts {
    <script type="text/javascript">
        // passing a function to $ is a shortcut for document.ready
        $(function () {
            $('#Cancel').click(function () {
                window.location.href = '@Url.Action("Index")';
            });
        });
    </script>
}

<h2>@ViewBag.Title</h2>

<p>Are you sure you want to delete the contact information for @Model.FullName?</p>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" />
        <input type="button" value="Cancel" id="Cancel" />
    </p>
}

HeathHopkins/Views/Contact/Details.cshtml
@model HeathHopkins.Models.Contact

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Contact</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FirstName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FirstName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.MiddleInitial)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MiddleInitial)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LastName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LastName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Address1)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address1)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Address2)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address2)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.City)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.City)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.State)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.State)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PostalCode)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PostalCode)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PhoneNumber)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PhoneNumber)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Email)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HeathHopkins/Views/Contact/Edit.cshtml
@model HeathHopkins.Models.Contact

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@{Html.RenderPartial("Form", Model);}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HeathHopkins/Views/Contact/Form.cshtml
@model HeathHopkins.Models.Contact

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

        @*@Html.HiddenFor(model => model.Id)*@

        <div class="editor-label">
            @Html.LabelFor(model => model.FirstName):
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FirstName)
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MiddleInitial):
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MiddleInitial)
            @Html.ValidationMessageFor(model => model.MiddleInitial)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastName):
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastName)
            @Html.ValidationMessageFor(model => model.LastName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Address1):
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address1)
            @Html.ValidationMessageFor(model => model.Address1)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Address2):
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address2)
            @Html.ValidationMessageFor(model => model.Address2)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.City):
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.City)
            @Html.ValidationMessageFor(model => model.City)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.State):
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.State)
            @Html.ValidationMessageFor(model => model.State)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PostalCode):
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PostalCode)
            @Html.ValidationMessageFor(model => model.PostalCode)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PhoneNumber):
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PhoneNumber)
            @Html.ValidationMessageFor(model => model.PhoneNumber)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email):
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <p>
            <input type="submit" value="Save" />
            @Html.ActionLink("Back to Contacts", "Index")
        </p>
}

HeathHopkins/Views/Contact/Index.cshtml
@model IEnumerable<HeathHopkins.Models.Contact>

@{
    ViewBag.Title = "Contacts";
}

@section Scripts {
    <script type="text/javascript">
        $(function () {
            $('#add-contact-form').submit(function (e) {
                if (console && console.log) {
                    console.log('intercepted "add contact" button click in javascript');
                    // i could do some other stuff here and/or cancel the click.
                }
            });
        });
    </script>
}

<h1>Contacts</h1>

@if (Model.Count() > 0) {
    <table>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th></th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
    </table>
}
else {
    <p>You don't have any contacts defined.</p>
}

@using (Html.BeginForm("Create", "Contact", FormMethod.Get, new { id = "add-contact-form" }))
{
    <input type="submit" value="Add Contact" />
}